# Generated by Django 4.1 on 2024-04-14 07:58

import account.services.utils_services
import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to='user/images', validators=[common.validators.validate_file_size])),
                ('bio', models.CharField(max_length=400, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=account.services.utils_services.create_new_code_number, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True, db_column='last_modification_time')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='spaces_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(db_column='last_modified_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fau_space',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.EmailField(max_length=254, null=True)),
                ('invite_expiration_date', models.DateTimeField(null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.space')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('space', 'user')},
            },
        ),
        migrations.AddField(
            model_name='space',
            name='users',
            field=models.ManyToManyField(related_name='spaces', through='account.UserAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='current_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.space'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_member', to='account.space'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
