# Generated by Django 4.1 on 2024-04-08 23:04

import account.services.utils_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(default=account.services.utils_services.create_new_code_number, max_length=50, unique=True),
        ),
    ]
