# Generated by Django 4.1.5 on 2023-01-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
