# Generated by Django 4.1.5 on 2023-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='invite_expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
