# Generated by Django 4.1 on 2023-04-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_bio_user_linkedin_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_default_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='default_space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_member', to='account.space'),
        ),
    ]
