# Generated by Django 4.1.7 on 2023-04-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_space_is_default_spaces_user_default_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_default_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_member', to='account.space'),
        ),
    ]
