# Generated by Django 4.1.7 on 2023-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_default_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_default_space',
            field=models.BooleanField(default=False),
        ),
    ]
