# Generated by Django 4.1.1 on 2022-09-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_alter_answertemplate_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
