# Generated by Django 4.1.1 on 2022-09-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0009_rename_value_metricimpact_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricimpact',
            name='quality_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_impacts', to='baseinfo.qualityattribute'),
        ),
    ]
