# Generated by Django 4.1.1 on 2022-10-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0012_alter_metric_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attribute/images')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='baseinfo.qualityattribute')),
            ],
        ),
    ]
