# Generated by Django 3.2.16 on 2022-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0019_alter_profiledsl_dsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
