# Generated by Django 3.2.16 on 2022-12-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0020_alter_metric_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledsl',
            name='profile',
        ),
    ]
