# Generated by Django 4.1.5 on 2023-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0023_profiletag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletag',
            options={'verbose_name': 'Profile Tag', 'verbose_name_plural': 'Profile Tags'},
        ),
        migrations.RemoveField(
            model_name='profiletag',
            name='profile',
        ),
        migrations.AddField(
            model_name='profiletag',
            name='profiles',
            field=models.ManyToManyField(related_name='tags', to='baseinfo.assessmentprofile'),
        ),
    ]
