# Generated by Django 4.1.5 on 2023-01-04 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0025_expertgroup_assessmentprofile_expert_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertgroup',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertgroup',
            name='picture',
            field=models.ImageField(null=True, upload_to='expertgroup/images'),
        ),
        migrations.AddField(
            model_name='expertgroup',
            name='users',
            field=models.ManyToManyField(related_name='expert_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertgroup',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
