# Generated by Django 4.1.5 on 2023-01-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0026_expertgroup_description_expertgroup_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
