# Generated by Django 4.1.5 on 2023-01-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0028_assessmentprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentprofile',
            old_name='description',
            new_name='summary',
        ),
    ]
