# Generated by Django 4.1.5 on 2023-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0029_rename_description_assessmentprofile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assessmentprofile',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
