# Generated by Django 4.1.5 on 2023-02-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0037_alter_expertgroup_bio_alter_expertgroup_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertgroup',
            options={'permissions': [('manage_expert_group', 'Manage Expert Groups')]},
        ),
    ]
