# Generated by Django 4.1.5 on 2023-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221116_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='invite_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
