# Generated by Django 4.1.5 on 2023-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_useraccess_invite_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
