# Generated by Django 4.1.1 on 2022-09-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_qualityattributevalue_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityattributevalue',
            old_name='temp_id',
            new_name='id',
        ),
    ]
