# Generated by Django 4.1.5 on 2023-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_assessmentproject_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentproject',
            name='code',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
