# Generated by Django 4.1 on 2022-09-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Profile',
                'verbose_name_plural': 'Assessment Profiles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('assessment_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='assessmentbaseinfo.assessmentprofile')),
            ],
            options={
                'verbose_name': 'Assessment Subject',
                'verbose_name_plural': 'Assessment Subjects',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='QualityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('assessment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentbaseinfo.assessmentsubject')),
            ],
            options={
                'verbose_name': 'Quality Attribute',
                'verbose_name_plural': 'Quality Attributes',
            },
        ),
        migrations.CreateModel(
            name='MetricImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentbaseinfo.metric')),
                ('quality_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentbaseinfo.qualityattribute')),
            ],
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('assessment_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_categories', to='assessmentbaseinfo.assessmentprofile')),
            ],
            options={
                'verbose_name': 'Metric Category',
                'verbose_name_plural': 'Metric Categories',
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentbaseinfo.metriccategory'),
        ),
        migrations.AddField(
            model_name='metric',
            name='quality_attributes',
            field=models.ManyToManyField(through='assessmentbaseinfo.MetricImpact', to='assessmentbaseinfo.qualityattribute'),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='metric_categories',
            field=models.ManyToManyField(related_name='assessment_subjects', to='assessmentbaseinfo.metriccategory'),
        ),
    ]
