# Generated by Django 4.1.1 on 2022-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentbaseinfo', '0002_answertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='caption',
            field=models.TextField(),
        ),
    ]
