# Generated by Django 4.1.1 on 2022-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentbaseinfo', '0005_assessmentprofile_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='metriccategory',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
