# Generated by Django 4.1.1 on 2022-09-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentbaseinfo', '0007_remove_metriccategory_index_metric_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_templates', to='assessmentbaseinfo.metric'),
        ),
    ]
