# Generated by Django 4.1.1 on 2022-09-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentbaseinfo', '0010_alter_metricimpact_quality_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricimpact',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_impacts', to='assessmentbaseinfo.metric'),
        ),
    ]
