# Generated by Django 4.1.1 on 2022-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_metriccategory_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metriccategory',
            name='index',
        ),
        migrations.AddField(
            model_name='metric',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
