# Generated by Django 3.2.16 on 2022-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0016_alter_profileimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertemplate',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qualityattribute',
            name='index',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
