# Generated by Django 3.2.16 on 2022-12-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0017_auto_20221116_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDsl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsl', models.FileField(upload_to='profile/images')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dsl', to='baseinfo.assessmentprofile')),
            ],
        ),
    ]
