# Generated by Django 3.2.16 on 2022-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0018_profiledsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledsl',
            name='dsl',
            field=models.FileField(upload_to='profile/dsl'),
        ),
    ]
