# Generated by Django 3.2.16 on 2022-12-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0021_remove_profiledsl_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledsl',
            old_name='dsl',
            new_name='dsl_file',
        ),
    ]
