# Generated by Django 4.1.5 on 2023-01-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0027_expertgroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentsubject',
            name='assessment_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subjects', to='baseinfo.assessmentprofile'),
        ),
        migrations.AlterField(
            model_name='metriccategory',
            name='assessment_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_categories', to='baseinfo.assessmentprofile'),
        ),
    ]
