# Generated by Django 4.1.5 on 2023-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0031_assessmentprofile_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertgroup',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='expertgroup',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
