# Generated by Django 4.1.5 on 2023-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0036_alter_expertgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertgroup',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expertgroup',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
