# Generated by Django 4.1.5 on 2023-02-05 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0038_alter_expertgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertgroupaccess',
            name='invite_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='expertgroupaccess',
            name='invite_expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expertgroupaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expertgroupaccess',
            unique_together={('expert_group', 'user')},
        ),
    ]
