# Generated by Django 4.1.5 on 2023-02-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0040_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('title', 'assessment_profile')},
        ),
    ]
