# Generated by Django 4.1.5 on 2023-02-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0042_alter_expertgroup_about_alter_expertgroup_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentprofile',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='assessmentprofile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessmentprofile',
            name='expert_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='baseinfo.expertgroup'),
        ),
        migrations.AlterField(
            model_name='assessmentprofile',
            name='summary',
            field=models.TextField(),
        ),
    ]
