# Generated by Django 4.1.5 on 2023-02-10 12:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0045_alter_assessmentsubject_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityattributeimage',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='subjectimage',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='answertemplate',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='expertgroup',
            name='picture',
            field=models.ImageField(null=True, upload_to='expertgroup/images', validators=[common.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profiledsl',
            name='dsl_file',
            field=models.FileField(upload_to='profile/dsl', validators=[common.validators.validate_file_size, common.validators.validate_dsl_extension]),
        ),
        migrations.AlterUniqueTogether(
            name='answertemplate',
            unique_together={('index', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='qualityattribute',
            unique_together={('title', 'assessment_subject'), ('index', 'assessment_subject')},
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.DeleteModel(
            name='QualityAttributeImage',
        ),
        migrations.DeleteModel(
            name='SubjectImage',
        ),
    ]
