# Generated by Django 4.1.7 on 2023-04-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0047_alter_profiledsl_dsl_file_optionvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertemplate',
            options={'verbose_name': 'Answer Template', 'verbose_name_plural': 'Answer Templates'},
        ),
    ]
