# Generated by Django 4.1.7 on 2023-04-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0048_alter_answertemplate_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together={('title', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='qualityattribute',
            unique_together={('title', 'assessment_subject'), ('index', 'assessment_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('title', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
        migrations.AlterField(
            model_name='assessmentsubject',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qualityattribute',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together={('title', 'assessment_profile'), ('code', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='qualityattribute',
            unique_together={('code', 'assessment_subject'), ('title', 'assessment_subject'), ('index', 'assessment_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('title', 'assessment_profile'), ('code', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
    ]
