# Generated by Django 4.1.7 on 2023-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0049_alter_assessmentsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together={('title', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='qualityattribute',
            unique_together={('title', 'assessment_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('title', 'assessment_profile'), ('index', 'assessment_profile')},
        ),
    ]
