# Generated by Django 4.1.7 on 2023-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0050_alter_assessmentsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubject',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='qualityattribute',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
