# Generated by Django 4.1.5 on 2023-04-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0051_alter_assessmentsubject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityattribute',
            name='assessment_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_attributes', to='baseinfo.assessmentsubject'),
        ),
    ]
