# Generated by Django 4.1.5 on 2023-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0052_alter_qualityattribute_assessment_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricimpact",
            name="weight",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="qualityattribute",
            name="weight",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
