# Generated by Django 4.1 on 2023-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0052_alter_qualityattribute_assessment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprofile',
            name='profile_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='metricimpact',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qualityattribute',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
