# Generated by Django 4.1.5 on 2023-05-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0053_metricimpact_weight_qualityattribute_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaturityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("value", models.PositiveSmallIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maturity_levels",
                        to="baseinfo.assessmentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
                "unique_together": {("value", "profile"), ("title", "profile")},
            },
        ),
        migrations.CreateModel(
            name="LevelCompetenceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "maturity_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_competence_relations",
                        to="baseinfo.maturitylevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_competence_relation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_competences",
                        to="baseinfo.levelcompetencerelation",
                    ),
                ),
                (
                    "maturity_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_competences",
                        to="baseinfo.maturitylevel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="metricimpact",
            name="maturity_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_impacts",
                to="baseinfo.maturitylevel",
            ),
        ),
    ]
