# Generated by Django 4.1.5 on 2023-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0055_remove_levelcompetence_level_competence_relation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricimpact",
            name="level",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
