# Generated by Django 4.1 on 2023-05-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0056_alter_metricimpact_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledsl',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsl', to='baseinfo.assessmentprofile'),
        ),
    ]
