# Generated by Django 4.2.2 on 2023-06-11 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0057_profiledsl_profile"),
    ]

    operations = [migrations.RenameField('Questionnaire', 'assessment_profile', 'assessment_kit'),
                  migrations.RenameField('AssessmentSubject', 'assessment_profile', 'assessment_kit'),]
