# Generated by Django 4.2.2 on 2023-06-13 09:46

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0059_auto_20230611_1804"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentkit",
            options={
                "ordering": ["title"],
                "verbose_name": "Assessment Kit",
                "verbose_name_plural": "Assessment Kits",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentkittag",
            options={
                "verbose_name": "Assessment Kit Tag",
                "verbose_name_plural": "Assessment Kit Tags",
            },
        ),
        migrations.RenameField(
            model_name="assessmentkitdsl",
            old_name="profile",
            new_name="assessment_kit",
        ),
        migrations.RenameField(
            model_name="assessmentkitlike",
            old_name="profile",
            new_name="assessment_kit",
        ),
        migrations.RenameField(
            model_name="assessmentkittag",
            old_name="profiles",
            new_name="assessmentkits",
        ),
        migrations.RenameField(
            model_name="maturitylevel",
            old_name="profile",
            new_name="assessment_kit",
        ),
        migrations.AlterField(
            model_name="assessmentkit",
            name="expert_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessmentkits",
                to="baseinfo.expertgroup",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentkitdsl",
            name="dsl_file",
            field=models.FileField(
                upload_to="assessment_kit/dsl",
                validators=[common.validators.validate_file_size],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="maturitylevel",
            unique_together={("title", "assessment_kit"), ("value", "assessment_kit")},
        ),
    ]
