# Generated by Django 4.1.7 on 2023-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0060_alter_assessmentkit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='may_not_be_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
