# Generated by Django 4.1 on 2023-07-19 11:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0061_metric_may_not_be_applicable'),
    ]
    operations = [
        migrations.RenameField(model_name='MetricImpact',old_name='metric',new_name='question'),
        migrations.RenameField(model_name='OptionValue', old_name='metric_impact', new_name='question_impact'),
        migrations.RenameField(model_name='AnswerTemplate',old_name='metric',new_name='question'),
    ]