# Generated by Django 4.1 on 2023-07-19 11:12

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0062_auto_20230718_1556'),
    ]
    operations = [
                migrations.RenameModel('MetricImpact', 'QuestionImpact'),
                migrations.RenameModel('Metric', 'Question'),
    ]