# constants.py

# Sheet names
SHEET_MATURITY_LEVELS = "MaturityLevels"
SHEET_QUALITY_ATTRIBUTES = "QualityAttributes"
SHEET_QUESTIONS = "Questions"
SHEET_QUESTIONARIES = "Questionaries"
SHEET_OPTIONS = "AnswerOptions"

# Constants for headers in sheets
HEADER_MATURITY_LEVELS = 1     # Second row is used as the header
HEADER_QUALITY_ATTRIBUTES = 0  # First row is used as the header
HEADER_QUESTIONARIES = 0
HEADER_QUESTIONS = 1
HEADER_OPTIONS = 0

# Column names
SHEET_MATURITY_LEVELS_TITLE = "Title"
SHEET_MATURITY_LEVELS_DESCRIPTION = "Description"

SHEET_QUALITY_ATTRIBUTES_SUBJECT_NAME = "Subject Name"
SHEET_QUALITY_ATTRIBUTES_SUBJECT_TITLE = "Subject Title"
SHEET_QUALITY_ATTRIBUTES_SUBJECT_DESCRIPTION = "Subject Description"

SHEET_ATTRIBUTES_ATTRIBUTE_NAME = "Attribute Name"
SHEET_ATTRIBUTES_ATTRIBUTE_TITLE = "Attribute Title"
SHEET_ATTRIBUTES_ATTRIBUTE_DESCRIPTION = "Attribute Description"

SHEET_QUESTIONARIES_NAME = "Name"
SHEET_QUESTIONARIES_TITLE = "Title"
SHEET_QUESTIONARIES_DESCRIPTION = "Description"

SHEET_QUESTIONS_CODE = "Code"
SHEET_QUESTIONS_TITLE = "Question"
SHEET_QUESTIONS_OPTIONS = "Options"
SHEET_QUESTIONS_DESCRIPTION = "Description"
SHEET_QUESTIONS_QUESTIONARIES = "Questionaries"
SHEET_QUESTIONS_MATURITY = "Maturity"
SHEET_QUESTIONS_MAY_NOT_BE_APPLICABLE = "Not Applicable"
SHEET_QUESTIONS_ADVISABLE = "Advisable"
SHEET_QUESTIONS_START_AFFECTS_COLUMN_INDEX = 8

SHEET_OPTIONS_RANGE_NAME = "Range Name"
SHEET_OPTIONS_TITLE = "Option Title"
SHEET_OPTIONS_VALUE = "Option Value"

# Other constants
DEFAULT_DESCRIPTION = " "
DSL_FILE_EXT = ".ak"
QUESTION_FILE_PREFIX = "questions_"  # Prefix for question files

# Output file names
OUTPUT_FILE_LEVELS = "levels.ak"
OUTPUT_FILE_QUALITY_ATTRIBUTES = "quality-attribute.ak"
OUTPUT_FILE_QUESTIONNAIRES = "questionnaires.ak"
OUTPUT_FILE_SUBJECTS = "subjects.ak"

# Zip file name
OUTPUT_ZIP_FILE = "kit.zip"
DSL_FOLDER_NAME = "kit"

