# Generated by Django 4.1.1 on 2022-09-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_metricvalue_value_metricvalue_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('color_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentproject',
            name='status',
            field=models.CharField(choices=[('WEAK', 'WEAK'), ('RISKY', 'RISKY'), ('NORMAL', 'NORMAL'), ('GOOD', 'GOOD'), ('OPTIMIZED', 'OPTIMIZED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessmentproject',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assessment.color'),
        ),
    ]
