# Generated by Django 4.1.1 on 2022-10-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_default_space_user_current_space'),
        ('assessment', '0009_alter_qualityattributevalue_maturity_level_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentproject',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.space'),
        ),
    ]
