# Generated by Django 4.1.5 on 2023-02-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_space_code_alter_space_title'),
        ('baseinfo', '0046_remove_qualityattributeimage_attribute_and_more'),
        ('assessment', '0011_alter_assessmentproject_code_alter_color_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentproject',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.space'),
        ),
        migrations.AlterField(
            model_name='qualityattributevalue',
            name='maturity_level_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='qualityattributevalue',
            name='quality_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_attribute_values', to='baseinfo.qualityattribute'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentproject',
            unique_together={('title', 'space')},
        ),
    ]
