# Generated by Django 4.1.5 on 2023-02-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_space_owner'),
        ('assessment', '0012_alter_assessmentproject_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentproject',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='account.space'),
        ),
    ]
