# Generated by Django 4.1.7 on 2023-04-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_default_space'),
        ('assessment', '0014_evidencerelation_evidence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentproject',
            unique_together={('title', 'space')},
        ),
        migrations.AlterField(
            model_name='assessmentproject',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentproject',
            unique_together={('title', 'space'), ('code', 'space')},
        ),
    ]
