# Generated by Django 4.2.2 on 2023-06-11 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0019_alter_qualityattributevalue_maturity_level_value"),
    ]

    operations = [migrations.RenameField('AssessmentProject', 'assessment_profile', 'assessment_kit'),]
