# Generated by Django 4.1 on 2023-07-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_auto_20230718_1556'),
    ]

    operations = [
            migrations.RenameModel('MetricValue', 'QuestionValue'),

    ]