# Generated by Django 4.1.1 on 2022-09-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentbaseinfo', '0002_answertemplate'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentbaseinfo.answertemplate'),
        ),
    ]
