# Generated by Django 4.1.1 on 2022-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_color_assessmentproject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentproject',
            name='code',
            field=models.SlugField(max_length=100),
        ),
    ]
