# Generated by Django 4.1.1 on 2022-09-28 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_qualityattributevalue_quality_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityattributevalue',
            name='id',
        ),
        migrations.AlterField(
            model_name='qualityattributevalue',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
