# Generated by Django 4.1.1 on 2022-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_rename_temp_id_qualityattributevalue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityattributevalue',
            name='maturity_level_value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
